import { Campaign, PlatformMetrics } from './types';

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: '1',
    creator: 'GB7N5B3WQK6ZTY72W4M8Q9XL6K4D7E5R3T2Y1U0P9O8I7U6Y5T4R3E2W',
    creatorName: 'Stellar GreenGrid Initiative',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    title: 'SolarGrid: Off-grid Solar Microgrid on Stellar Soroban',
    tagline: 'Trustless community-funded solar microgrid with smart energy metering on Stellar Testnet.',
    description: 'SolarGrid brings clean, autonomous solar energy to rural communities. Instead of relying on opaque subsidies, our smart meters verify solar watt-hours directly on the Stellar blockchain. Funding is locked in a Soroban escrow contract and only released when verified installation proofs and energy output telemetry are uploaded to IPFS and approved by backers.',
    category: 'Green Tech',
    imageUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=1200&auto=format&fit=crop&q=80',
    totalGoal: 15000,
    totalRaised: 12450,
    totalReleased: 5000,
    donorCount: 38,
    status: 'Active',
    createdAt: '2026-08-15T10:00:00Z',
    currentMilestoneIndex: 1,
    milestones: [
      {
        index: 0,
        description: 'Phase 1: Procurement of 50kW Monocrystalline Solar Panels & Inverters',
        amount: 5000,
        deadline: '2026-09-15T00:00:00Z',
        proofHash: 'QmSolarInverterBillOfLadingAndCustomsClearance2026',
        proofTitle: 'Hardware Shipment Manifest & On-site Delivery Inspection',
        proofDescription: 'All 50kW Tier-1 solar panels and smart hybrid inverters successfully arrived on site. Customs clearance certificates and serial numbers verified against manufacturer spec sheet.',
        proofMediaUrl: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?w=800&auto=format&fit=crop&q=80',
        submittedAt: '2026-08-20T14:30:00Z',
        status: 'Released',
        votesFor: 11200,
        votesAgainst: 150,
      },
      {
        index: 1,
        description: 'Phase 2: Microgrid Substation Construction & Battery Bank Wiring',
        amount: 6000,
        deadline: '2026-10-10T00:00:00Z',
        proofHash: 'QmBatteryBankInstallationTelemetricSignoffStellar',
        proofTitle: 'Substation Foundation & 120kWh LFP Battery Bank Installation',
        proofDescription: 'Battery rack installation completed with multi-tier thermal sensor arrays. Grid interconnect switchgear tested at 480V with zero thermal anomalies.',
        proofMediaUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
        submittedAt: '2026-08-28T09:15:00Z',
        status: 'InReview',
        votesFor: 8450,
        votesAgainst: 600,
      },
      {
        index: 2,
        description: 'Phase 3: Smart IoT Metering Integration & Community Grid Activation',
        amount: 4000,
        deadline: '2026-11-20T00:00:00Z',
        status: 'Pending',
        votesFor: 0,
        votesAgainst: 0,
      }
    ],
    updates: [
      {
        id: 'u1',
        date: '2026-08-28',
        author: 'Stellar GreenGrid Initiative',
        title: 'Phase 2 Proof Submitted for Community Voting!',
        content: 'We have uploaded the full installation video, engineering diagrams, and battery telemetry logs to IPFS. Please cast your vote in the voting widget below!',
        likes: 24,
      },
      {
        id: 'u2',
        date: '2026-08-21',
        author: 'Stellar GreenGrid Initiative',
        title: 'Phase 1 Tranche Released — Hardware Installed',
        content: 'Thanks to the 98.7% approval quorum, the first tranche of 5,000 XLM has been unlocked from the Soroban escrow. Hardware installation is already underway!',
        likes: 41,
      }
    ]
  },
  {
    id: '2',
    creator: 'GDK8V2P4Q1W9M6Z3Y8X5T2R7E4W1Q0O9I8U7Y6T5R4E3W2Q1P0O9I8U7',
    creatorName: 'AeroPulse Health Labs',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: 'OpenVent: Low-Cost Decentralized ICU Ventilator System',
    tagline: 'Open-source, FDA-aligned portable ICU emergency ventilator blueprints & embedded firmware.',
    description: 'OpenVent produces rugged, low-cost pneumatic ventilators designed for remote clinics and disaster response zones. All firmware is open-source and audited. Campaign funds are disbursed in tranches conditional on bench testing validation, biomedical calibration reports, and open-hardware repo publication.',
    category: 'Healthcare',
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=1200&auto=format&fit=crop&q=80',
    totalGoal: 20000,
    totalRaised: 20000,
    totalReleased: 8000,
    donorCount: 64,
    status: 'Funded',
    createdAt: '2026-08-10T12:00:00Z',
    currentMilestoneIndex: 1,
    milestones: [
      {
        index: 0,
        description: 'Pneumatic Circuit Prototyping & Flow Sensor Calibration',
        amount: 8000,
        deadline: '2026-09-01T00:00:00Z',
        proofHash: 'QmOpenVentPneumaticFlowCalibrationReportV1',
        proofTitle: 'Flow Calibration Lab Certificate & Oscilloscope Logs',
        proofDescription: 'Verified ±2% Tidal Volume accuracy across 100 continuous test hours on artificial lung simulators.',
        proofMediaUrl: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=800&auto=format&fit=crop&q=80',
        submittedAt: '2026-08-25T11:00:00Z',
        status: 'Released',
        votesFor: 18500,
        votesAgainst: 300,
      },
      {
        index: 1,
        description: 'Embedded RTOS Firmware & UI Touchscreen Integration',
        amount: 7000,
        deadline: '2026-10-15T00:00:00Z',
        proofHash: 'QmOpenVentFirmwareBinaryAndSecurityAuditSigned',
        proofTitle: 'Firmware v1.2 Build Binary & MISRA-C Compliance Audit',
        proofDescription: 'Zero critical memory leaks detected under 72h stress test. Real-time FiO2 alarm triggers within 250ms.',
        proofMediaUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&auto=format&fit=crop&q=80',
        submittedAt: '2026-08-29T16:20:00Z',
        status: 'InReview',
        votesFor: 12400,
        votesAgainst: 800,
      },
      {
        index: 2,
        description: 'Clinical Simulator Testing & Global Open Source Release',
        amount: 5000,
        deadline: '2026-11-30T00:00:00Z',
        status: 'Pending',
        votesFor: 0,
        votesAgainst: 0,
      }
    ]
  },
  {
    id: '3',
    creator: 'GCD7M4W2K9P1Q8Z5Y3X6T0R2E7W4Q1O9I8U7Y6T5R4E3W2Q1P0O9I8U7',
    creatorName: 'AquaPure Decentralized Water DAO',
    creatorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    title: 'AquaSensor: On-Chain Groundwater Contaminant Monitor',
    tagline: 'IoT spectrophotometry sensor pods recording arsenic and heavy metal levels to Soroban.',
    description: 'Providing real-time groundwater safety data directly onto the immutable Stellar ledger. Local communities fund deployment of solar-powered water sensing buoys with escrow milestones unlocking upon physical deployment and continuous API uptime proof.',
    category: 'Infrastructure',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=1200&auto=format&fit=crop&q=80',
    totalGoal: 10000,
    totalRaised: 6850,
    totalReleased: 0,
    donorCount: 22,
    status: 'Active',
    createdAt: '2026-08-24T08:30:00Z',
    currentMilestoneIndex: 0,
    milestones: [
      {
        index: 0,
        description: 'Sensor PCB Fabrication & Optical Chamber Assembly',
        amount: 4000,
        deadline: '2026-09-30T00:00:00Z',
        status: 'Pending',
        votesFor: 0,
        votesAgainst: 0,
      },
      {
        index: 1,
        description: 'Field Deployment of 20 Buoys in Brahmaputra Basin',
        amount: 4000,
        deadline: '2026-11-15T00:00:00Z',
        status: 'Pending',
        votesFor: 0,
        votesAgainst: 0,
      },
      {
        index: 2,
        description: 'Public Web Dashboard & Soroban Oracles Live Feed',
        amount: 2000,
        deadline: '2026-12-20T00:00:00Z',
        status: 'Pending',
        votesFor: 0,
        votesAgainst: 0,
      }
    ]
  },
  {
    id: '4',
    creator: 'GA9X8Y7Z6W5V4U3T2S1R0Q9P8O7N6M5L4K3J2I1H0G9F8E7D6C5B4A3',
    creatorName: 'Rustlings Stellar Foundation',
    creatorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    title: 'SorobanDev: Interactive WebAssembly Contract Sandbox',
    tagline: 'In-browser interactive Soroban smart contract debugger and visual compiler.',
    description: 'An open-source IDE and step-debugger running Soroban Rust contracts directly in browser WebAssembly. Zero-setup developer onboarding for the entire Stellar developer ecosystem.',
    category: 'Open Source',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&auto=format&fit=crop&q=80',
    totalGoal: 12000,
    totalRaised: 12000,
    totalReleased: 12000,
    donorCount: 52,
    status: 'Completed',
    createdAt: '2026-07-01T10:00:00Z',
    currentMilestoneIndex: 2,
    milestones: [
      {
        index: 0,
        description: 'Core WASM Engine & Bytecode Interpreter',
        amount: 4000,
        deadline: '2026-07-20T00:00:00Z',
        proofHash: 'QmSorobanWasmCoreEngineGithubReleaseV01',
        proofTitle: 'WASM Compiler v0.1 Release & 100 Unit Tests',
        proofMediaUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
        status: 'Released',
        votesFor: 11800,
        votesAgainst: 100,
      },
      {
        index: 1,
        description: 'Monaco Editor Integration & Soroban Syntax Highlighting',
        amount: 4000,
        deadline: '2026-08-10T00:00:00Z',
        proofHash: 'QmMonacoSorobanIntegrationAndLspV1',
        proofTitle: 'Language Server Protocol & In-Browser Build Demo',
        proofMediaUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
        status: 'Released',
        votesFor: 11950,
        votesAgainst: 50,
      },
      {
        index: 2,
        description: 'Testnet Contract Deployer & Stellar Wallet Bridge',
        amount: 4000,
        deadline: '2026-08-25T00:00:00Z',
        proofHash: 'QmSorobanTestnetDeployerFreighterBridgeSigned',
        proofTitle: 'Freighter 1-Click Testnet Deployment Module',
        proofMediaUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
        status: 'Released',
        votesFor: 12000,
        votesAgainst: 0,
      }
    ]
  }
];

export const PLATFORM_METRICS: PlatformMetrics = {
  totalVolumeXLM: 49300,
  totalCampaigns: 4,
  successfulCampaigns: 2,
  activeEscrowXLM: 24300,
  totalDonors: 176,
  totalMilestonesReleased: 6,
};
